baserow:
  base_url: https://api.baserow.io
  api_token: w5YLuEJF6pTm2HfrmlFBQpJYRhMiurdG
  sku_mapping_table_id: 602281
  combo_sku_table_id: 598588
  inventory_table_id: 599869
  processed_sales_data_table_id: 598432
  category_table_id: 598433
  purchase_orders_table_id: 598617
  catalogue_table_id: 600174
  inventory_warehouse_columns:
  - TLCQ
  - PNQ2
  - DEL4
  - CCX1
  - BLR8
  - BOM7
  - BLR7
  - BOM5
  - CCU1
  - DEL5
  - DEX3
  - PNQ3
cache:
  directory: .rms_cache
  expiry_days: 5
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file_name: rms_app.log
platforms:
- name: Amazon
  slug: amazon
  accounts:
  - name: Main Account
    slug: main
    sku_column: Sku
    quantity_column: Quantity
- name: Flipkart
  slug: flipkart
  accounts:
  - name: Account CSTE (FK)
    slug: fk_acc_CSTE
    sku_column: SKU ID
    quantity_column: Final Sale Units
  - name: Account Giantleap (FK)
    slug: fk_acc_giantleap
    sku_column: SKU ID
    quantity_column: Final Sale Units
- name: Meesho
  slug: meesho
  accounts:
  - name: Account CSTE (MS)
    slug: ms_acc_CSTE
    sku_column: SKU
    quantity_column: Quantity
  - name: Account Rudra (MS)
    slug: ms_acc_rudra
    sku_column: SKU
    quantity_column: Quantity
default_sales_report_columns:
  sku_column: SKU
  quantity_column: Quantity
data_paths:
  uploaded_sales_root: uploaded_data
  sales_reports_subdir: sales
replenishment_table:
  feature_date_format: '%d-%b-%Y'
