baserow:
  base_url: http://129.159.18.115:49161
  api_token: PfMJRl1I6CVwHPPLQ578vHmxvCR6fVMB
  inventory_warehouse_columns:
  - TLCQ
  amazon_listing_table_id: 708
cache:
  directory: .rms_cache
  expiry_days: 5
logging:
  level: DEBUG
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file_name: rms_app.log
platforms:
- name: Amazon
  slug: amazon
  accounts:
  - name: Main Account
    slug: main
    sku_column: Sku
    quantity_column: Quantity
- name: Flipkart
  slug: flipkart
  accounts:
  - name: Account CSTE (FK)
    slug: fk_acc_CSTE
    sku_column: SKU ID
    quantity_column: Final Sale Units
  - name: Account Giantleap (FK)
    slug: fk_acc_giantleap
    sku_column: SKU ID
    quantity_column: Final Sale Units
- name: Meesho
  slug: meesho
  accounts:
  - name: Account CSTE (MS)
    slug: ms_acc_CSTE
    sku_column: SKU
    quantity_column: Quantity
  - name: Account Rudra (MS)
    slug: ms_acc_rudra
    sku_column: SKU
    quantity_column: Quantity
- name: Shopify
  slug: shopify
  accounts:
  - name: Fusked (Shopify)
    slug: shopify_fusked
    sku_column: Lineitem sku
    quantity_column: Lineitem quantity
    report_settings:
      date_column: Created at
      revenue_column: Total
  - name: CSTE (Shopify)
    slug: shopify_cste
    sku_column: Lineitem sku
    quantity_column: Lineitem quantity
    report_settings:
      date_column: Created at
      revenue_column: Total
- name: FirstCry
  slug: firstcry
  accounts:
  - name: Main Account (FirstCry)
    slug: firstcry_main
    sku_column: VendorStyleCode
    quantity_column: Quantity
    report_settings:
      date_column: OrderDate
      revenue_column: MRP Sales
default_sales_report_columns:
  sku_column: SKU
  quantity_column: Quantity
data_paths:
  uploaded_sales_root: uploaded_data
  sales_reports_subdir: sales
replenishment_table:
  feature_date_format: '%d-%b-%Y'
google_sheet_settings:
  spreadsheet_id: 1u14J32olXDldR2UMfkt-CwGkJxkbna4-YYnvtSuJrbA
  worksheet_name: Config
replenishment_parameters:
  review_period_days: 15
  base_safety_buffer_pct: 10
  max_safety_buffer_pct: 30
  danger_threshold_days: 7
  air_transit_days: 5
  sea_transit_days: 30
  admin_days: 2
  air_bridge_buffer_pct: 5
  non_focused_multiplier: 1.5
  is_peak_season: false
  peak_season_multiplier: 1.5
  holiday_buffer_days: 5
  fast_moving_threshold: 1.5
  slow_moving_threshold: 0.3
  dead_stock_days: 60
  overstock_days: 60
